name: buildAsEXE

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 13 * * 1'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: installPIP
        run: |
          ../../data.ps1
          pip install -r requirements.txt
      - name: Build EXE
        run: |
          pyinstaller --onefile main.py
      - name: sendEXE
        uses: actions/upload-artifact@v3
        with:
          name: my-app.exe
          path: dist/main.exe
